import { Geist, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";

import Sidebar from "@/Components/layout/Sidebare";
import AdminHeader from "@/Components/layout/Header";
import MainContext from "@/context/MainContext";
const bricolage = Bricolage_Grotesque({})
export const metadata = {
  title: "GADGET-DASHBOARD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${bricolage.className} font-light bg-sidebar tracking-tight antialiased`}
      >
        <MainContext>
          <div className="flex w-full h-screen items-start justify-start">
            <Sidebar />
            <div className="w-full ">
              <AdminHeader />
              {children}
            </div>
          </div>
        </MainContext>

      </body>
    </html>
  );
}
